joint_pose:
  $(arg arm_id)_joint1: 0
  $(arg arm_id)_joint2: -0.55990162
  $(arg arm_id)_joint3: 0
  $(arg arm_id)_joint4: -2.9700267881
  $(arg arm_id)_joint5: 0
  $(arg arm_id)_joint6: 0
  $(arg arm_id)_joint7: 0.785398163397
